apiVersion: v1
kind: Secret
metadata:
    name: helloworld
    labels:
        app: helloworld
        chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
        release: '{{ .Release.Name }}'
        heritage: '{{ .Release.Service }}'
type: Opaque
data:
  mysecret: {{ .Values.helloworld.secrets.mySecret | b64enc | quote }}
  mysecretTwo: {{ .Values.helloworld.secrets.mySecretTwo | b64enc | quote }}